### ISSUE TITLE
Demo runs fine on PC+Quest with Oculus Link, but does not run on Quest standalone.

### ISSUE THREAD

**Issue by horatiu665** [antilatency/Unity.AltTrackingOculusHmdSample#1]
Hi. I updated the project with the SDK 3.0.0 using unity package manager / git integration, and installed the Antilatency Service 3.0.0 on the quest device as well as on my computer. I tested a simple scene with 1 alt on hmd dongle as UsbRadioSocket, and connected the dongle to the PC as well as the oculus using Link cable, and it works, I can also see the tracking inside Oculus, and clearly the space is corrected to match the real space, so both oculus tracking and antilatency tracking are working. By the way, it feels quite magical!

Anyway, next step was to make a build on the quest and I ran into trouble - the antilatency service showed the dongle and alt being connected when I checked, however the unity build does not detect them. Oculus tracking works in the build but the antilatency tracking doesn't. I looked with adb logcat and I found this to be pretty suspicious, turns out the ADN is not able to initialize. I don't know if it's useful to you but here's the log in question:

```

2021/06/19 12:54:05.252 5119 5145 Warn System.err java.lang.SecurityException: User has not given 10090/com.Antilatency.encyabab_latency permission to access device /dev/bus/usb/001/002
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.os.Parcel.createException(Parcel.java:2071)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.os.Parcel.readException(Parcel.java:2039)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.os.Parcel.readException(Parcel.java:1987)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:123)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:143)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at com.antilatency.usblibrarycommon.AbstractAndroidUsbLibrary.getUsbDeviceInfo(AbstractAndroidUsbLibrary.java:44)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.os.Handler.dispatchMessage(Handler.java:103)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.os.Looper.loop(Looper.java:214)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
2021/06/19 12:54:05.252 5119 5145 Warn System.err Caused by: android.os.RemoteException: Remote stack trace:
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at com.android.server.usb.UsbUserSettingsManager.checkPermission(UsbUserSettingsManager.java:179)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at com.android.server.usb.UsbSerialReader.getSerial(UsbSerialReader.java:96)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.hardware.usb.IUsbSerialReader$Stub.onTransact(IUsbSerialReader.java:84)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.os.Binder.execTransactInternal(Binder.java:1021)
2021/06/19 12:54:05.252 5119 5145 Warn System.err 	at android.os.Binder.execTransact(Binder.java:994)
2021/06/19 12:54:05.252 5119 5145 Fatal spdlog [12:54:05.252][005145][critical] Create network failed; Error 
2021/06/19 12:54:05.253 5119 5145 Error Unity Failed to create Antilatency Device Network 
2021/06/19 12:54:05.253 5119 5145 Error Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2021/06/19 12:54:05.253 5119 5145 Error Unity 
2021/06/19 12:54:05.254 5119 5145 Error Unity Native network is null 
2021/06/19 12:54:05.254 5119 5145 Error Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2021/06/19 12:54:05.254 5119 5145 Error Unity 
2021/06/19 12:54:05.258 5119 5145 Info OVRPlugin UnityPluginLoad called
2021/06/19 12:54:05.292 5119 5145 Info Unity Unity v2019.4.17f1, Oculus Utilities v1.49.0, OVRPlugin v1.49.0, SDK v1.1.34.0. 
2021/06/19 12:54:05.292 5119 5145 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2021/06/19 12:54:05.292 5119 5145 Info Unity 
2021/06/19 12:54:05.311 5119 5145 Info Unity SystemHeadset Oculus_Quest 
2021/06/19 12:54:05.311 5119 5145 Info Unity (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
2021/06/19 12:54:05.311 5119 5145 Info Unity 

```

I tried to look online for this issue of asking android for permission to access USB but had no luck. I didn't get a prompt on startup about allowing access to usb devices, except one about if I want to "open Antilatency Service to handle this Product" and I said Okay. 

I tried this on three separate oculus devices, and I also tried sdk/service version 2.1.0 with no luck.

Can you recommend a fix?

By the way I'm using the kit from University of Southern Denmark.

**Comment by psarev** [comment]
Fixed in 3.3.0 release with intent-filter for usb permissions : 0fcf4423ae9d6fd6ee8d23f9cdc214f24cd99d74
